name: test

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      CGO_CFLAGS_ALLOW: -Xpreprocessor
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install linux deps
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo add-apt-repository -y ppa:strukturag/libde265
          sudo add-apt-repository -y ppa:strukturag/libheif
          sudo add-apt-repository -y ppa:lovell/cgif
          sudo apt-get -y install libopenjp2-7 libcgif-dev
          sudo apt-get -y install libvips-dev

      - name: Get dependencies
        run: make get

      - name: Test
        run: make test

      - name: Coveralls
        if: matrix.os == 'ubuntu-20.04'
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
